# portdb

FROM yarnpkg/node-yarn:node7

ENV MONGODB_URI=mongodb://localhost:27017/portdb
ENV SERVICE_DIR=/opt/portdb

WORKDIR ${SERVICE_DIR}

COPY portdb/ ./
RUN yarn install

EXPOSE 8000
CMD ["yarn", "start"]
